### ISSUE TITLE
Question about data used for experiments in the paper

### ISSUE THREAD

**Issue by ElisaNguyen** [salesforce/fast-influence-functions#21]
Hello! 

I liked your paper very much and was wondering if you could share the test set you used for the experiment described in "5.4 Quality of Influence Estimations"? If I understand correctly, this experiment is done with the 3-label MNLI dataset, right? 

Thank you very much!

**Comment by HanGuo97** [comment]
Hi, thanks for your interest!

You can find more details in Appendix B.3. TLDR: this experiment involves re-training the model (but with certain examples removed).

Hope this helps!

**Comment by ElisaNguyen** [comment]
Thank you for the quick response! I am trying to replicate this removing and retraining experiment and I was wondering if you could share the exact test set (data instances) that you used in this experiment.

**Comment by HanGuo97** [comment]
Got it; thanks for the explanation! It has been a while, but I think the data was programmatically generated. I would take a look at [this](https://github.com/salesforce/fast-influence-functions/blob/6052b409d304e9bde6f5cad08c672ca9d6ee1dcb/experiments/mnli.py#L54).

**Comment by ElisaNguyen** [comment]
Perfect! By any chance, do you still have the source files of `CORRECT_INDICES` and `INCORRECT_INDICES`? 

```
CORRECT_INDICES = sorted([
    # e.g., `KNN-recall.only-correct.50.0.pth.g0301.ll.unc.edu`
    int(f.split("/")[-1].split(".")[3])
    for f in glob(os.path.join(
        constants.MNLI_RETRAINING_INFLUENCE_OUTPUT_BASE_DIR,
        "*only-correct*")
    )
])
INCORRECT_INDICES = sorted([
    # e.g., `KNN-recall.only-correct.50.0.pth.g0301.ll.unc.edu`
    int(f.split("/")[-1].split(".")[3])
    for f in glob(os.path.join(
        constants.MNLI_RETRAINING_INFLUENCE_OUTPUT_BASE_DIR,
        "*only-incorrect*")
    )

**Comment by HanGuo97** [comment]
I would not count on this if they were not part of the open source.

Sorry, I wish I could be more helpful :/

**Comment by ElisaNguyen** [comment]
No problem in that case! Thank you very much :)
